### ISSUE TITLE
SqlEx Method方法参数强类型化

### ISSUE THREAD

**Issue by raintean** [sqlex/sqlex#4]
该设计旨在于增强SqlEx Method参数的类型安全

#### 1. 预支持类型
```java
// 基本类型
java.lang.Boolean, java.lang.Byte,
java.lang.Short, java.lang.Integer, java.lang.Long, java.lang.Float, java.lang.Double,
java.math.BigDecimal, java.math.BigInteger,

//字符 / 二进制数据
java.lang.Character, java.lang.String,
java.lang.Byte[], java.sql.Blob, java.io.InputStream, java.io.Reader

//时间
java.sql.Date, java.sql.Time, java.sql.Timestamp, java.util.Date,
java.time.LocalDate, java.time.LocalTime, java.time.LocalDateTime,
java.time.OffsetTime, java.time.OffsetDateTime, java.time.ZonedDateTime, java.time.Instant,
```
#### 2. 自定义类型
参数转换器接口
```
public interface ParameterConverter<P, D> {
    D convert(P parameter);
}
```
如果类型FooBar要作为参数, 则必须为其定义参数转换器, 并在SqlEx Config中注册

> FooBarParameterConverter.java
```
package me.danwi.sqlex.example.dao.converters;

class FooBarParameterConverter<FooBar, String> {
    String convert(FooBar value) {
        // ...
    }
}
```

> sqlex.yaml 配置文件
```yaml
# 根包
package: me.danwi.sqlex.exmaple.dao

# 类型转换器
converters:
  - me.danwi.sqlex.example.dao.converters.FooBarParameterConverter
 
```

converters 列表在上面的转换器优先级高于下面转换器

### 任务列表

- [x] core - 完成ParameterConverter的定义(#39 #40)
- [x] 编辑器插件 - sqlm参数类型错误提示(#47)
- [x] 编辑器插件 - 配置文件智能支持(#42 #45)
- [x] 编辑器插件 - 编写自定义类型转换器时的错误提示(#44)
- [x] 编译插件 - 编译时的类型check(#53)
- [x] 编译插件 - 把转换器配置通过注解放入生成的Repository接口中(#46)

**Comment by WJY-JY** [comment]
## sqlex 支持参数类型转换表

sqlex 默认数据库字符统一使用`utf8`字符集，不再考虑`NATIONAL [CHARACTER`类型支持，例如`NCHAR,NVARCHAR,LONGNVARCHAR`，参考[详细原因](https://dev.mysql.com/doc/refman/8.0/en/charset-national.html)
| JAVA类型                   | SQL类型                       | 使用JDBC驱动方法                                                        |
|--------------------------|-----------------------------|-------------------------------------------------------------------|
| java.lang.Boolean        | BIT<br/>BOOLEAN             | void setBoolean(int parameterIndex, boolean x)                    |
| java.lang.Byte           | TINYINT                     | void setByte(int parameterIndex, byte x)                          |
| java.lang.Short          | SMALLINT                    | void setShort(int parameterIndex, short x)                        |
| java.lang.Integer        | INTEGER                     | void setInt(int parameterIndex, int x)                            |
| java.lang.Long           | BIGINT                      | void setLong(int parameterIndex, long x)                          |
| java.lang.Float          | REAL                        | void setFloat(int parameterIndex, float x)                        |
| java.lang.Double         | DOUBLE                      | void setDouble(int parameterIndex, double x)                      |
| java.lang.Character      | VARCHAR                     | void setString(int parameterIndex, String x)                      |
| java.lang.String         | VARCHAR<br/>LONGVARCHAR     | void setString(int parameterIndex, String x)                      |
| java.math.BigDecimal     | NUMERIC                     | void setBigDecimal(int parameterIndex, BigDecimal x)              |
| java.math.BigInteger     | NUMERIC                     | void setBigDecimal(int parameterIndex, BigDecimal x)              |
| java.lang.Byte[]         | VARBINARY<br/>LONGVARBINARY | void setBytes(int parameterIndex, byte x[]）                       |
| java.sql.Ref             | REF                         | void setRef (int parameterIndex, Ref x)                           |
| java.sql.Blob            | BLOB                        | void setBlob (int parameterIndex, Blob x)                         |
| java.sql.Clob            | CLOB                        | void setClob (int parameterIndex, Clob x)                         |
| java.sql.Array           | ARRAY                       | void setArray (int parameterIndex, Array x)                       |
| java.net.URL             | DATALINK                    | void setURL(int parameterIndex, java.net.URL x)                   |
| java.sql.RowId           | ROWID                       | void setRowId(int parameterIndex, RowId x)                        |
| java.sql.NClob           | NCLOB                       | void setNClob(int parameterIndex, NClob value)                    |
| java.sql.SQLXML          | XML                         | void setSQLXML(int parameterIndex, SQLXML xmlObject)              |
| java.sql.Date            | DATE                        | void setDate(int parameterIndex, java.sql.Date x)                 |
| java.sql.Time            | TIME                        | void setTime(int parameterIndex, java.sql.Time x)                 |
| java.sql.Timestamp       | TIMESTAMP                   | void setTimestamp(int parameterIndex, java.sql.Timestamp x)       |
| java.util.Date           | TIMESTAMP                   | void setTimestamp(int parameterIndex, java.sql.Timestamp x)       |
| java.time.LocalDate      | DATE                        | void setDate(int parameterIndex, java.sql.Date x)                 |
| java.time.LocalTime      | TIME                        | void setTime(int parameterIndex, java.sql.Time x)                 |
| java.time.LocalDateTime  | TIMESTAMP                   | void setTimestamp(int parameterIndex, java.sql.Timestamp x)       |
| java.time.OffsetTime     | TIME                        | void setTime(int parameterIndex, java.sql.Time x)                 |
| java.time.OffsetDateTime | TIMESTAMP                   | void setTimestamp(int parameterIndex, java.sql.Timestamp x)       |
| java.time.ZonedDateTime  | TIMESTAMP                   | void setTimestamp(int parameterIndex, java.sql.Timestamp x)       |
| java.time.Instant        | TIMESTAMP                   | void setTimestamp(int parameterIndex, java.sql.Timestamp x)       |
| AsciiInputStream         | LONGVARCHAR                 | void setAsciiStream(int parameterIndex, java.io.InputStream x)    |
| BinaryInputStream        | LONGVARBINARY               | void setBinaryStream(int parameterIndex, java.io.InputStream x)   |
| CharacterReader          | LONGVARCHAR                 | void setCharacterStream(int parameterIndex,java.io.Reader reader) |
| ClobReader               | CLOB<br/>LONGVARCHAR        | void setClob(int parameterIndex, Reader reader)                   |
| BlobInputStream          | LONGVARBINARY<br/>BLOB      | void setBlob(int parameterIndex, InputStream inputStream)         |
| NClobReader              | LONGNVARCHAR<br/>NCLOB      | void setNClob(int parameterIndex, Reader reader)                  |
